/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.proliferay.myportlet.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.proliferay.myportlet.model.GuestBook;
import com.proliferay.myportlet.model.GuestBookModel;
import com.proliferay.myportlet.model.GuestBookSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GuestBook service. Represents a row in the &quot;GB_GuestBook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GuestBookModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GuestBookImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GuestBookImpl
 * @generated
 */
@JSON(strict = true)
public class GuestBookModelImpl
	extends BaseModelImpl<GuestBook> implements GuestBookModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a guest book model instance should use the <code>GuestBook</code> interface instead.
	 */
	public static final String TABLE_NAME = "GB_GuestBook";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"guestBookId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("guestBookId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GB_GuestBook (uuid_ VARCHAR(75) null,guestBookId LONG not null primary key,groupId LONG,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table GB_GuestBook";

	public static final String ORDER_BY_JPQL =
		" ORDER BY guestBook.guestBookId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GB_GuestBook.guestBookId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long STATUS_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long GUESTBOOKID_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GuestBook toModel(GuestBookSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GuestBook model = new GuestBookImpl();

		model.setUuid(soapModel.getUuid());
		model.setGuestBookId(soapModel.getGuestBookId());
		model.setGroupId(soapModel.getGroupId());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GuestBook> toModels(GuestBookSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<GuestBook> models = new ArrayList<GuestBook>(soapModels.length);

		for (GuestBookSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GuestBookModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _guestBookId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGuestBookId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _guestBookId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GuestBook.class;
	}

	@Override
	public String getModelClassName() {
		return GuestBook.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GuestBook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GuestBook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestBook, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((GuestBook)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GuestBook, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GuestBook, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GuestBook)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GuestBook, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GuestBook, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GuestBook>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GuestBook.class.getClassLoader(), GuestBook.class,
			ModelWrapper.class);

		try {
			Constructor<GuestBook> constructor =
				(Constructor<GuestBook>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GuestBook, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GuestBook, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GuestBook, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GuestBook, Object>>();
		Map<String, BiConsumer<GuestBook, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GuestBook, ?>>();

		attributeGetterFunctions.put("uuid", GuestBook::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<GuestBook, String>)GuestBook::setUuid);
		attributeGetterFunctions.put("guestBookId", GuestBook::getGuestBookId);
		attributeSetterBiConsumers.put(
			"guestBookId",
			(BiConsumer<GuestBook, Long>)GuestBook::setGuestBookId);
		attributeGetterFunctions.put("groupId", GuestBook::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<GuestBook, Long>)GuestBook::setGroupId);
		attributeGetterFunctions.put("status", GuestBook::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<GuestBook, Integer>)GuestBook::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", GuestBook::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<GuestBook, Long>)GuestBook::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", GuestBook::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<GuestBook, String>)GuestBook::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", GuestBook::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<GuestBook, Date>)GuestBook::setStatusDate);
		attributeGetterFunctions.put("companyId", GuestBook::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<GuestBook, Long>)GuestBook::setCompanyId);
		attributeGetterFunctions.put("userId", GuestBook::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<GuestBook, Long>)GuestBook::setUserId);
		attributeGetterFunctions.put("userName", GuestBook::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<GuestBook, String>)GuestBook::setUserName);
		attributeGetterFunctions.put("createDate", GuestBook::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GuestBook, Date>)GuestBook::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", GuestBook::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GuestBook, Date>)GuestBook::setModifiedDate);
		attributeGetterFunctions.put("name", GuestBook::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<GuestBook, String>)GuestBook::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getGuestBookId() {
		return _guestBookId;
	}

	@Override
	public void setGuestBookId(long guestBookId) {
		_guestBookId = guestBookId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(GuestBook.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GuestBook.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GuestBook toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GuestBook>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GuestBookImpl guestBookImpl = new GuestBookImpl();

		guestBookImpl.setUuid(getUuid());
		guestBookImpl.setGuestBookId(getGuestBookId());
		guestBookImpl.setGroupId(getGroupId());
		guestBookImpl.setStatus(getStatus());
		guestBookImpl.setStatusByUserId(getStatusByUserId());
		guestBookImpl.setStatusByUserName(getStatusByUserName());
		guestBookImpl.setStatusDate(getStatusDate());
		guestBookImpl.setCompanyId(getCompanyId());
		guestBookImpl.setUserId(getUserId());
		guestBookImpl.setUserName(getUserName());
		guestBookImpl.setCreateDate(getCreateDate());
		guestBookImpl.setModifiedDate(getModifiedDate());
		guestBookImpl.setName(getName());

		guestBookImpl.resetOriginalValues();

		return guestBookImpl;
	}

	@Override
	public int compareTo(GuestBook guestBook) {
		long primaryKey = guestBook.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GuestBook)) {
			return false;
		}

		GuestBook guestBook = (GuestBook)obj;

		long primaryKey = guestBook.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GuestBookModelImpl guestBookModelImpl = this;

		guestBookModelImpl._originalUuid = guestBookModelImpl._uuid;

		guestBookModelImpl._originalGroupId = guestBookModelImpl._groupId;

		guestBookModelImpl._setOriginalGroupId = false;

		guestBookModelImpl._originalStatus = guestBookModelImpl._status;

		guestBookModelImpl._setOriginalStatus = false;

		guestBookModelImpl._originalCompanyId = guestBookModelImpl._companyId;

		guestBookModelImpl._setOriginalCompanyId = false;

		guestBookModelImpl._setModifiedDate = false;

		guestBookModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GuestBook> toCacheModel() {
		GuestBookCacheModel guestBookCacheModel = new GuestBookCacheModel();

		guestBookCacheModel.uuid = getUuid();

		String uuid = guestBookCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			guestBookCacheModel.uuid = null;
		}

		guestBookCacheModel.guestBookId = getGuestBookId();

		guestBookCacheModel.groupId = getGroupId();

		guestBookCacheModel.status = getStatus();

		guestBookCacheModel.statusByUserId = getStatusByUserId();

		guestBookCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = guestBookCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			guestBookCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			guestBookCacheModel.statusDate = statusDate.getTime();
		}
		else {
			guestBookCacheModel.statusDate = Long.MIN_VALUE;
		}

		guestBookCacheModel.companyId = getCompanyId();

		guestBookCacheModel.userId = getUserId();

		guestBookCacheModel.userName = getUserName();

		String userName = guestBookCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			guestBookCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			guestBookCacheModel.createDate = createDate.getTime();
		}
		else {
			guestBookCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			guestBookCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			guestBookCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		guestBookCacheModel.name = getName();

		String name = guestBookCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			guestBookCacheModel.name = null;
		}

		return guestBookCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GuestBook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GuestBook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestBook, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GuestBook)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GuestBook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GuestBook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestBook, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GuestBook)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GuestBook>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _guestBookId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private long _columnBitmask;
	private GuestBook _escapedModel;

}